ghci: install setuptools python module needed by ninja
without installing this on the github actions workers, ninja
fails to find the 'distutils' module

this fixes the following error on the github actions workers

```
/opt/podman/qemu/bin/gdbus-codegen ui/dbus-display1.xml --glib-min-required 2.64 --output-directory /Users/runner/work/podman-machine-qemu/podman-machine-qemu/qemu-8.2.0/build/ui --interface-prefix org.qemu. --c-namespace QemuDBus --generate-c-code dbus-display1
Traceback (most recent call last):
  File "/opt/podman/qemu/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/opt/podman/qemu/share/glib-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "/opt/podman/qemu/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/opt/podman/qemu/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
ninja: build stopped: subcommand failed.
make[1]: *** [run-ninja] Error 1
make: *** [build] Error 2
```

Signed-off-by: Anjan Nath <kaludios@gmail.com>